### ISSUE TITLE
Room Bot Crash

### ISSUE THREAD

**Issue by dwenger01** [giantotter/giantotter_public#386]
Running with tips of master as of Saturday, 1/23/2016, and some local changes to create a speech manager.

Initially was running with the Restaurant level and 2 clients (using an empty group code for each client).  In the first run the 2 clients operated correctly (one was customer, one was waitress); however, subsequent runs failed to start up a waitress client, so I was left with a customer and a spectator.

Since I wanted to test TTS via player chat, and I needed to turn on TTS I opted to use my rest_dave level that I had created earlier in the week (so I could enable TTS in the project settings).  Also, I opted to start setting a unique group code on each run since that seemed to solve the issue with avoiding having a client set to spectator.

I probably had run 10 - 15 subsequent runs with a different group code each time, and everything worked as expected, but then on one of my runs I realized that neither client would connect for multiplayer mode.

There were no unusual errors that were new (I had been seeing a VOIP-related error since apparently VOIP was set to enabled in the project settings).

**Comment by jefforkin** [comment]
Thanks Dave.  Two questions -- first, prior to setting a new group code every time, did you run into the same issue with rest_dave that you saw with Restaurant, where you couldn't get a waitress again?  Or did you just go ahead with a new group code every time, so you didn't get a chance to see if that issue would have re-occurred with rest_dave?

Second, just wanted to double check that in Unity you did set the CHANNEL_CONNECTIONS constant to #connections2?  Just wondering, because we have seen issues if that is not set -- roombot has trouble detecting disconnections.

**Comment by dwenger01** [comment]
Hi Jeff.  I had made your suggested changes in NetProviderIRC.cs (from your post in slack) prior to doing any testing yesterday.

I didn't see the same issue in rest_dave because at that point I'd started to change the group code each time, so unfortunately I don't have a data point on that for you.

**Comment by jefforkin** [comment]
Here is the stack trace for Dave's crash.  I can easily see how to prevent this in the future, but don't understand why it happened.  Basically, when Dave's Waitress quit, roombot tried to remove her from her room, but her session ID was different than the Waitress actually in the room.

I'm wondering if we get a new session ID when a scene changes?  Dave, do you remember if the scene timer expired and started a new scene?  This is something we can test.

Connected to pydev debugger (build 141.2569)
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5.4\helpers\pydev\pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5.4\helpers\pydev\pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/GitHub/giantotter/server/matchmaking/room_bot.py", line 212, in <module>
    main()
  File "C:/GitHub/giantotter/server/matchmaking/room_bot.py", line 207, in main
    bot.start()
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\bot.py", line 265, in start
    super(SingleServerIRCBot, self).start()
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 1283, in start
    self.reactor.process_forever()
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 276, in process_forever
    self.process_once(timeout)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 257, in process_once
    self.process_data(i)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 214, in process_data
    c.process_data()
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 583, in process_data
    self._process_line(line)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 683, in _process_line
    self._handle_event(event)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 687, in _handle_event
    self.reactor._handle_event(self, event)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 396, in _handle_event
    result = handler.callback(connection, event)
  File "C:\GitHub\giantotter\server\api\venv\lib\site-packages\irc\client.py", line 1246, in _dispatcher
    method(connection, event)
  File "C:/GitHub/giantotter/server/matchmaking/room_bot.py", line 57, in on_quit
    channel = self.matchmaker.remove_occupant(e.source.nick)
  File "C:/GitHub/giantotter/server/matchmaking\Bots\matchmaker.py", line 168, in remove_occupant
    self.state_keepers[room.name].remove_occupant(occupant)
  File "C:/GitHub/giantotter/server/matchmaking\Bots\statekeeper.py", line 139, in remove_occupant
    self.role_assigner.remove_player(player)
  File "C:/GitHub/giantotter/server/matchmaking\Bots\statekeeper.py", line 59, in remove_player
    self.player_queue.remove(player)
ValueError: list.remove(x): x not in list

**Comment by dwenger01** [comment]
The scene timer may have expired in my last working test prior to not being able to connect again.  This definitely happened multiple times during the tests I was running.  Also I noticed that if it took one of the clients too long to connect w.r.t. the other client, that when the 2nd client finally connected it would restart the countdown on the first client.  I think this is by design based on comments I've seen between you and Graham, but I wasn't sure if it was causing a new instance of that first client's player to be created.

Another point of note is that after my first run (when I was running without a group code) it was the waitress that the room would not spawn for me.  I could always get a customer and a spectator, but it seemed like the room thought the waitress was already there.  Not sure how long that waitress persisted, but is it possible that it is that waitress instance that the room bot was trying to remove?  Is it possible that after many runs we created a waitress with a session id that matched the session id from a prior run?

**Comment by jefforkin** [comment]
We figured out how to crash the roombot the way Dave did on Saturday.  It is related to the way we name IRC channels that serve as rooms -- using the initial player's username.  We should name channels uniquely (GUID), otherwise it is possible for the same user to join the same channel with a different groupcode, and roombot gets very confused.  

I will fix this, but unsure what caused the initial issue of always being customer or spectator.  If Dave was not using a group code, there is a small chance that someone else on the internet was actually online as the waitress.

**Comment by jefforkin** [comment]
I fixed the issue that caused the exception that Dave saw, but could not find the root cause of the original issue that led to all of this -- where Dave was only able to join as Customer or Spectator.
