### ISSUE TITLE
Exception from show tips

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#798]
Trying to run Otto with sarah's new Olivia logs.

When I get to show tips, I get this exception.  Issue with a non-ascii character in the tips data.

Exception in thread Thread-37:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\GitHub\giantotter\lib\otter\bot_cognition.py", line 77, in run
    self.cog.execute_action(self.next_action)
  File "C:\GitHub\giantotter\lib\otter\bot_cognition.py", line 284, in execute_action
    context_type, next_obs.aux_data)]
  File "C:\GitHub\giantotter\lib\otter\bot_actions.py", line 107, in execute_action
    actor_name, target_entity, context_entity, aux_data)
  File "C:\GitHub\giantotter\lib\otter\bot_simulation_office.py", line 75, in render_phys_act
    category_strings.append('{} {}'.format(category, tip))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 76: ordinal not in range(128)

**Comment by dwenger01** [comment]
Jeff, you might want to check the tips data for non-standard quotation marks.  That's what the \u2019 character is.  I noticed this issue in School Life when I was copying over data from the slide deck related to cue cards.  There was a quote used that was a unicode character, not ascii.
